plotting_config = {
    "vetoNu0": {
        "label": "VetoNu0_charge",
        "xlabel": "Charge [pC]",
        "title": r"FASER$\nu$ veto station, layer 1",
        "scale": 1,
        "name": "vetoNuCharge0",
    },
    "vetoNu1": {
        "label": "VetoNu1_charge",
        "xlabel": "Charge [pC]",
        "title": r"FASER$\nu$ veto station, layer 2",
        "scale": 1,
        "name": "vetoNuCharge1",
    },
    "veto10": {
        "label": "VetoSt10_charge",
        "xlabel": "Charge [pC]",
        "title": "Veto station, layer 1",
        "scale": 1,
        "name": "vetoCharge10",
    },
    # "veto11": {
    #     "label": "VetoSt11_charge",
    #     "xlabel": "Charge [pC]",
    #     "title": "Veto station, layer 2",
    #     "scale": 1,
    #     "name": "vetoCharge11",
    # },
    "veto20": {
        "label": "VetoSt20_charge",
        "xlabel": "Charge [pC]",
        "title": "Veto station, layer 3",
        "scale": 1,
        "name": "vetoCharge20",
    },
    "veto21": {
        "label": "VetoSt21_charge",
        "xlabel": "Charge [pC]",
        "title": "Veto station, layer 4",
        "scale": 1,
        "name": "vetoCharge21",
    },
    "timing0": {
        "label": "Timing0_charge",
        "xlabel": "Charge [pC]",
        "title": "Trigger station, layer 1",
        "scale": 1,
        "name": "timingCharge0",
    },
    "timing1": {
        "label": "Timing1_charge",
        "xlabel": "Charge [pC]",
        "title": "Trigger station, layer 2",
        "scale": 1,
        "name": "timingCharge1",
    },
    "timing2": {
        "label": "Timing2_charge",
        "xlabel": "Charge [pC]",
        "title": "Trigger station, layer 3",
        "scale": 1,
        "name": "timingCharge2",
    },
    "timing3": {
        "label": "Timing3_charge",
        "xlabel": "Charge [pC]",
        "title": "Trigger station, layer 4",
        "scale": 1,
        "name": "timingCharge3",
    },
    "preshower0": {
        "label": "Preshower0_charge",
        "xlabel": "Charge [pC]",
        "title": r"Pre-shower station, layer 0",
        "scale": 1,
        "name": "preshowerCharge0",
    },
    "preshower1": {
        "label": "Preshower1_charge",
        "xlabel": "Charge [pC]",
        "title": r"Pre-shower station, layer 1",
        "scale": 1,
        "name": "preshowerCharge1",
    },
    "calo0": {
        "label": "Calo0_charge",
        "xlabel": "Charge [pC]",
        "title": r"Calorimeter, layer 1",
        "scale": 1,
        "name": "caloCharge0",
    },
    "calo1": {
        "label": "Calo1_charge",
        "xlabel": "Charge [pC]",
        "title": r"Calorimeter, layer 2",
        "scale": 1,
        "name": "caloCharge1",
    },
    "calo2": {
        "label": "Calo2_charge",
        "xlabel": "Charge [pC]",
        "title": r"Calorimeter, layer 3",
        "scale": 1,
        "name": "caloCharge2",
    },
    "calo3": {
        "label": "Calo3_charge",
        "xlabel": "Charge [pC]",
        "title": r"Calorimeter, layer 4",
        "scale": 1,
        "name": "caloCharge3",
    },
    "theta_x": {
        "label": "Track_theta_x0",
        "xlabel": r"$\theta_x$ [mrad]",
        "title": "",
        "scale": 1e3,
        "name": "theta_x",
    },
    "theta_y": {
        "label": "Track_theta_y0",
        "xlabel": r"$\theta_y$ [mrad]",
        "title": "",
        "scale": 1e3,
        "name": "theta_y",
    },
    "pz": {
        "label": "Track_pz_charge0",
        "xlabel": r"$p_z$ [GeV]",
        "title": "",
        "scale": 1e-3,
        "name": "pz",
    },
    "chi2": {
        "label": "Track_Chi2",
        "xlabel": r"$\chi^2$",
        "title": "",
        "scale": 1,
        "name": "chi2",
    },
    "chi2_per_ndf": {
        "label": "Track_chi2_per_dof",
        "xlabel": r"$\chi^2$/NDF",
        "title": "",
        "scale": 1,
        "name": "chi2_per_ndf",
    },
    # "chi2_zoom": {
    #     "label": "Track_Chi2_2",
    #     "xlabel": r"$\chi^2$",
    #     "title": "",
    #     "scale": 1,
    #     "name": "chi2_2",
    # },
    "ndof": {
        "label": "Track_nDoF",
        "xlabel": r"nDoF",
        "title": "",
        "scale": 1,
        "name": "nDoF",
    },
    "x": {
        "label": "Track_x0",
        "xlabel": r"$x$ [mm]",
        "title": "",
        "scale": 1,
        "name": "x",
    },
    "y": {
        "label": "Track_y0",
        "xlabel": r"$y$ [mm]",
        "title": "",
        "scale": 1,
        "name": "y",
    },
    "theta_x_pos": {
        "label": "Track_theta_x0_pos",
        "xlabel": r"$\theta_{x, q>0}$ [mrad]",
        "title": "",
        "scale": 1e3,
        "name": "theta_x_pos",
    },
    "theta_x_neg": {
        "label": "Track_theta_x0_neg",
        "xlabel": r"$\theta_{x, q<0}$ [mrad]",
        "title": "",
        "scale": 1e3,
        "name": "theta_x_neg",
    },
    "theta_y_pos": {
        "label": "Track_theta_y0_pos",
        "xlabel": r"$\theta_{y, q>0}$ [mrad]",
        "title": "",
        "scale": 1e3,
        "name": "theta_y_pos",
    },
    "theta_y_neg": {
        "label": "Track_theta_y0_neg",
        "xlabel": r"$\theta_{y, q<0}$ [mrad]",
        "title": "",
        "scale": 1e3,
        "name": "theta_y_neg",
    },
}